### ISSUE TITLE
Poetry run pytest explainer metrics failure

### ISSUE THREAD

**Issue by andrelfnovaes** [holistic-ai/holisticai#101]
This is the output when running `poetry run pytest`:

![image](https://github.com/holistic-ai/holisticai/assets/40208986/66dc98ab-779b-4be0-86ab-3de878daa0de)

1 failed is reported: _There are no features for alpha=0.9, please select a higher value._

![image](https://github.com/holistic-ai/holisticai/assets/40208986/129cb031-8400-4bbd-8f69-452afbbc8159)

Summary:

![image](https://github.com/holistic-ai/holisticai/assets/40208986/a6de87a0-c33f-48a9-91d9-ed1322a912f5)

I am using WSL2.

**Comment by crismunoz** [comment]
Hi @andrelfnovaes  which python version are you using?

**Comment by andrelfnovaes** [comment]
Hi @crismunoz ,

Python 3.10, as written here: https://github.com/holistic-ai/holisticai/blob/main/CONTRIBUTING.md.

**Comment by Kleyt0n** [comment]
Already fixed in https://github.com/holistic-ai/holisticai/pull/102
