### ISSUE TITLE
measuring_bias_classification error

### ISSUE THREAD

**Issue by rosepolle** [holistic-ai/holisticai#34]
from holisticai.bias.plots import group_pie_plot, success_rate_plot

"success_rate_plot" --> cannot import

**Comment by Kleyt0n** [comment]
from holisticai.bias.plots import group_pie_plot, frequency_plot

or 

from holisticai.bias.plots import group_pie_plot, success_rate_curve

**Comment by fracarfer5** [comment]
Since nothing else was reported, I can infer the issue was solved. Therefore I am closing this issue ;)
