### ISSUE TITLE
DisparateImpactRemover is not importing in fresh installation

### ISSUE THREAD

**Issue by fracarfer5** [holistic-ai/holisticai#67]
**Sumary**

`DisparateImpactRemover` fails to import on a fresh installation of OS and conda environment.

**Steps for reproduction**

Package installed using: `pip install holisticai`

then:

```python
from holisticai.bias.mitigation.preprocessing import DisparateImpactRemover
```
the outcome is:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'DisparateImpactRemover' from 'holisticai.bias.mitigation.preprocessing' (/home/username/miniconda3/envs/venv/lib/python3.9/site-packages/holisticai/bias/mitigation/preprocessing/__init__.py)
```

**Version information**

- Operating system: Ubuntu 20.04 LTS
- Python version: 3.9.16
- holisticai version: 0.5.0

Thanks!

**Comment by crismunoz** [comment]
@fracarfer5 For mitigators you have to install the full version:
```bash
pip install holisticai[methods]
```

**Comment by fracarfer5** [comment]
Thanks!! It is working now
