### ISSUE TITLE
Incorrect documentations

### ISSUE THREAD

**Issue by crismunoz** [holistic-ai/holisticai#7]
In documentation of ExponentiatedGradientReduction in-processing mitigation method: this method has an 'estimator' stated as a parameter but does not actually take it as a parameter.

**Comment by fracarfer5** [comment]
Hi to all, there is an error while trying to replicate the tutorial: "Measuring Bias in classification", the error appears when the success_rate_function is imported. It seems to have been updated or changed to the frequency_plot function,  the tutorial and the figure title should be updated. 
![Screenshot 2023-03-02 100645](https://user-images.githubusercontent.com/44931423/222439799-f5ee3edc-9d61-44bb-8b43-28bd6057d532.png)
![Screenshot 2023-03-02 100719](https://user-images.githubusercontent.com/44931423/222439806-ca7ddc81-2595-4dcc-a9ba-8e03f58d6ba5.png)
